#version 460

// TODO: profile different workgroup geometries
// Maybe something more x oriented might be better for cache coherency
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;


#include "ch11_VoxelsRayTracing.glsl"
#include "ch11_VoxelsSsbo.glsl"
#include "ch11_VoxelsUtilities.glsl"

#include "shaders/Helpers.glsl"
#include "shaders/LightsBlock.glsl"
#include "shaders/LightUtilities.glsl"
#include "shaders/ViewProjectionBlock.glsl"


uniform vec3 u_AabbMin;
uniform float u_VoxelSize;
uniform bool u_AverageNormalByAxis;

uniform usampler3D u_AlbedoTexture;
uniform usampler3D u_NormalsTexture;

uniform writeonly restrict image3D u_IrradianceImage;


vec3 injectDirectLight(vec3 aShadingNormal, vec3 aLightDir, LightColors aColors)
{
    //#define MITIGATE_NORMALS
	#if defined(MITIGATE_NORMALS)
        vec3 weight = aShadingNormal * aShadingNormal;
        // calculate directional shading attenuation
        float rDotL = dot(vec3(1.0, 0.0, 0.0), aLightDir);
        float uDotL = dot(vec3(0.0, 1.0, 0.0), aLightDir);
        float fDotL = dot(vec3(0.0, 0.0, 1.0), aLightDir);

        rDotL = aShadingNormal.x > 0.0 ? max(rDotL, 0.0) : max(-rDotL, 0.0);
        uDotL = aShadingNormal.y > 0.0 ? max(uDotL, 0.0) : max(-uDotL, 0.0);
        fDotL = aShadingNormal.z > 0.0 ? max(fDotL, 0.0) : max(-fDotL, 0.0);
        // voxel shading average from all front sides
        float nDotL = rDotL * weight.x + uDotL * weight.y + fDotL * weight.z;
	#else
		if (u_AverageNormalByAxis)
        {
            aLightDir = abs(aLightDir);
        }
		float nDotL = dotPlus(aShadingNormal, aLightDir);
	#endif

    vec3 diffuse = nDotL * aColors.diffuse.rgb;
    return diffuse;
}


void main()
{
    if(any(greaterThanEqual(gl_GlobalInvocationID, uvec3(ub_GridDimension))))
    {
        return;
    }

    ivec3 voxelCoord = ivec3(gl_GlobalInvocationID);

    uvec4 voxelAlbedo = texelFetch(u_AlbedoTexture, voxelCoord, 0);
    vec4 albedo = vec4(voxelAlbedo) / 255;

    if (albedo.a == 0)
    {
        // Debug write
		//imageStore(u_IrradianceImage, voxelCoord, vec4(0, 1, 1, 1));
        return; // non-occupied
    }

    uvec4 voxelNormal = texelFetch(u_NormalsTexture, voxelCoord, 0);
    // Remap from [0, 1]^3 to [-1, 1]^3
    vec3 normal_world = ((vec3(voxelNormal.xyz) / 255) * 2) - 1;
    normal_world = normalize(normal_world);
	vec3 position_world = voxelToWorld(voxelCoord, u_VoxelSize, u_AabbMin);

    // Accumulator for irradiance
    vec3 irradiance = vec3(0);

    // Dummy variable to satisfy traversal API
	bvec3 unusedMask;

    //
    // Directional
    //
    for(uint directionalIdx = 0;
        directionalIdx != ub_DirectionalCount.x;
        ++directionalIdx)
    {
        DirectionalLight directional = ub_DirectionalLights[directionalIdx];
        vec3 lightDir_cam = -directional.direction.xyz;
        
		// We need the light in in the same space as the normal
		// TODO #perf: this info should be available in a buffer, not computed in each voxel
		vec3 lightDir_world = normalize(mat3(ub_cameraToWorld) * lightDir_cam);

        // Note: we traverse the voxel grid as an AABB with voxel of unit dimension
        // This allows to use the voxel grid coord as entry point in the AABB directly
		ivec3 shadowingVoxel =
			traverseVoxels(voxelCoord, lightDir_world, 
						   1, ub_GridDimension,
						   unusedMask, false/*test on texture*/,
						   getFullAabbBounds(), true/*skip self*/);
        float shadowFactor = (shadowingVoxel == ivec3(-1)) ? 1.f : 0.0f;

        irradiance += 
            injectDirectLight(normal_world, lightDir_world, directional.colors)
            * shadowFactor
            ;
    }

    //
    // Point
    //
	for(uint pointIdx = 0; pointIdx != ub_PointCount.x; ++pointIdx)
    {
        PointLight point = ub_PointLights[pointIdx];

		// TODO #perf: this info should be available in a buffer, not computed in each voxel
        vec3 lightPos_world = (ub_cameraToWorld * vec4(point.position.xyz, 1)).xyz;
        //vec3 lightPos_world = (ub_cameraToWorld * point.position).xyz;

		ivec3 lightPos_grid = worldToVoxel(lightPos_world, u_VoxelSize, u_AabbMin);
        // Set the light position to its voxel center
        lightPos_world = voxelToWorld(lightPos_grid, u_VoxelSize, u_AabbMin);

        vec3 lightRay_world = lightPos_world - position_world;
        float r = sqrt(dot(lightRay_world, lightRay_world));
        vec3 lightDir_world = lightRay_world / r;

        float falloff = attenuatePoint(point, r);

        GridBounds bounds = GridBounds(
            min(voxelCoord, lightPos_grid),
            max(voxelCoord, lightPos_grid));

		ivec3 shadowingVoxel =
			traverseVoxels(voxelCoord, lightDir_world, 
						   //u_VoxelSize, ub_GridDimension,
						   1, ub_GridDimension,
						   unusedMask, false/*test on texture*/,
						   bounds, true/*skip self*/);

        float shadowFactor = (shadowingVoxel == ivec3(-1)) ? 1.f : 0.0f;

        irradiance += 
            falloff *
            shadowFactor * 
            injectDirectLight(normal_world, lightDir_world, point.colors)
            ;
    }

    // Add ambient contribution
    irradiance += ub_AmbientColor.rgb;
    // Apply the voxel albedo to accumulated irradiance from all light sources
    irradiance *= albedo.rgb;

    // TODO: store correct occupancy (1 might be correct)
    imageStore(u_IrradianceImage, voxelCoord, vec4(irradiance, 1));
}